/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'users-payload': UsersPayloadAuthOperations;
  };
  blocks: {};
  collections: {
    accounts: Account;
    apartments: Apartment;
    markets: Market;
    searchLocations: SearchLocation;
    'users-payload': UsersPayload;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    apartments: ApartmentsSelect<false> | ApartmentsSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    searchLocations: SearchLocationsSelect<false> | SearchLocationsSelect<true>;
    'users-payload': UsersPayloadSelect<false> | UsersPayloadSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: UsersPayload;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsersPayloadAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  /**
   * Unique text identifier for the account
   */
  id: string;
  /**
   * Display name for the account
   */
  name: string;
  /**
   * Public-facing identifier (e.g. for APIs or URLs)
   */
  publicId: string;
  /**
   * When enabled, posts are automatically approved
   */
  autoApprove?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apartments".
 */
export interface Apartment {
  id: string;
  /**
   * Name or identifier for the apartment
   */
  name: string;
  status: 'draft' | 'published' | 'archived';
  type?: ('singleFamily' | 'multiFamily' | 'student' | 'military' | 'affordable' | 'senior') | null;
  housingType?: ('apartment' | 'penthouse' | 'duplex' | 'townhome') | null;
  enabledFeatures?: ('search' | 'seo' | 'ppc' | 'microsite' | 'designAssistant')[] | null;
  /**
   * IANA time zone (e.g. America/New_York)
   */
  timeZone?:
    | (
        | 'Pacific/Midway'
        | 'Pacific/Niue'
        | 'Pacific/Honolulu'
        | 'Pacific/Rarotonga'
        | 'America/Anchorage'
        | 'Pacific/Gambier'
        | 'America/Los_Angeles'
        | 'America/Tijuana'
        | 'America/Denver'
        | 'America/Phoenix'
        | 'America/Chicago'
        | 'America/Guatemala'
        | 'America/New_York'
        | 'America/Bogota'
        | 'America/Caracas'
        | 'America/Santiago'
        | 'America/Buenos_Aires'
        | 'America/Sao_Paulo'
        | 'Atlantic/South_Georgia'
        | 'Atlantic/Azores'
        | 'Atlantic/Cape_Verde'
        | 'Europe/London'
        | 'Europe/Berlin'
        | 'Africa/Lagos'
        | 'Europe/Athens'
        | 'Africa/Cairo'
        | 'Europe/Moscow'
        | 'Asia/Riyadh'
        | 'Asia/Dubai'
        | 'Asia/Baku'
        | 'Asia/Karachi'
        | 'Asia/Tashkent'
        | 'Asia/Calcutta'
        | 'Asia/Dhaka'
        | 'Asia/Almaty'
        | 'Asia/Jakarta'
        | 'Asia/Bangkok'
        | 'Asia/Shanghai'
        | 'Asia/Singapore'
        | 'Asia/Tokyo'
        | 'Asia/Seoul'
        | 'Australia/Brisbane'
        | 'Australia/Sydney'
        | 'Pacific/Guam'
        | 'Pacific/Noumea'
        | 'Pacific/Auckland'
        | 'Pacific/Fiji'
      )
    | null;
  /**
   * Account that owns or is associated with this apartment
   */
  accountId: string | Account;
  /**
   * Account (text)
   */
  account?: string | null;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * GeoJSON Point: { "type": "Point", "coordinates": [longitude, latitude] }
   */
  geojson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * URL of the marketing website
   */
  marketingWebsiteUrl?: string | null;
  /**
   * Phone number for prospects
   */
  prospectPhoneNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: string;
  /**
   * Combined market, submarket and state (auto-set)
   */
  name?: string | null;
  market?: string | null;
  submarket?: string | null;
  account?: string | null;
  /**
   * Account (relationship)
   */
  accountId?: (string | null) | Account;
  state?: string | null;
  location?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "searchLocations".
 */
export interface SearchLocation {
  id: string;
  /**
   * ID of the parent search location
   */
  parentId?: number | null;
  /**
   * Location type (e.g. State, City)
   */
  type: string;
  /**
   * Name of the search location
   */
  name: string;
  /**
   * Canonical full name (e.g. California, United States)
   */
  canonicalName?: string | null;
  /**
   * Country code (e.g. US)
   */
  country?: string | null;
  /**
   * Public identifier
   */
  publicId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users-payload".
 */
export interface UsersPayload {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users-payload';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'apartments';
        value: string | Apartment;
      } | null)
    | ({
        relationTo: 'markets';
        value: string | Market;
      } | null)
    | ({
        relationTo: 'searchLocations';
        value: string | SearchLocation;
      } | null)
    | ({
        relationTo: 'users-payload';
        value: string | UsersPayload;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users-payload';
    value: string | UsersPayload;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users-payload';
    value: string | UsersPayload;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  publicId?: T;
  autoApprove?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apartments_select".
 */
export interface ApartmentsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  type?: T;
  housingType?: T;
  enabledFeatures?: T;
  timeZone?: T;
  accountId?: T;
  account?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  geojson?: T;
  marketingWebsiteUrl?: T;
  prospectPhoneNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  name?: T;
  market?: T;
  submarket?: T;
  account?: T;
  accountId?: T;
  state?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "searchLocations_select".
 */
export interface SearchLocationsSelect<T extends boolean = true> {
  parentId?: T;
  type?: T;
  name?: T;
  canonicalName?: T;
  country?: T;
  publicId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users-payload_select".
 */
export interface UsersPayloadSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}